Home and About page
Bettenoch/Web_Development_Course pull request #1
Opened 2023-07-05 19:20 UTC by Bettenoch

**In this branch I made the following changes:**

- [ ] ♻Add home and about pages
- [ ] ♻Created speakers section in home page dynamically using Javascript  file.
- [ ] ♻Style home page and about page.
- [ ] ♻Add harmburger and close menu for mobile version
- [ ] ♻Personalized content to suite a web development course.
- [ ] ♻Add linters file
- [ ] ♻Add and updated readme file.

Thank you for reviewing my repository!!!🙂

2023-07-05 19:56 UTC, stanleySimeon requested changes
# Hi @Bettenoch, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have all linters check passed. please make sure you fix the issues before asking for another request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-05 20:36 UTC, Gambit142 reviewed
Hi @Bettenoch 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- The linters setup that you used was for `Javascript` projects. Kindly use the one for `HTML/SS + JavaScript` projects: https://github.com/microverseinc/linters-config/tree/master/html-css-js

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-05 20:43 UTC, Bettenoch commented
Hello @Gambit142 thank you for assistance. Concerning the change shoudl I reinstall the Linters files?

2023-07-05 20:44 UTC, Gambit142 commented
Hi @Bettenoch 👋,

I think that will be the best thing to do. 👍

2023-07-05 20:56 UTC, Bettenoch commented
I changed the linters file I really hope it is okay now

2023-07-05 22:45 UTC, mckent05 requested changes
Hi @Bettenoch, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍
- Good job working on your capstone project, keep going 🚀  


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
**OPTIONAL** - To help improve the UI and look of your site, I suggest you do not display the logo on the mobile menu. Please consider this 🙏 
Your project:
<img width="302" alt="weawewe" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/c00270b8-04f9-4202-97df-6d2e89fa844c">

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 22:45 UTC, mckent05 commented on README.md
> +- [Live Demo Link](https://bettenoch.github.io/Portfolio-Setup-Mobile-First)
- You have added the wrong link for your capstone project, I suggest you deploy your project live and add the correct link to your Readme in order to make it more professional 👍 👍

2023-07-05 22:45 UTC, mckent05 commented on README.md
> +
- According to the project requirements, you are required to give credit to [Cindy Shin](https://www.behance.net/adagio07) the author of the design you have used, please fix this 🙏

2023-07-05 22:45 UTC, mckent05 commented on index.html
> +        </article>
- You have done well so far, but you have not styled this page according to the design template, I suggest that the background blend for this section should cover the entire section and not just a part of it. Please fix this 🙏. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

- Also the font-color for the text I highlighted in the image below is not the same as seen in the design template. Please note that, though you are required to personalize the content of the page, you are required to stick to the design layout, background colors, font-style etc. Please fix this 🙏 
Your project:
- Please try to replicate the design template as closely as possible 😄 
<img width="950" alt="yw4w" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/b125e816-83d2-44db-a846-ed4e9e89f673">

Design template:
<img width="627" alt="rwegwrg" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/909712a9-7e0b-42f0-9401-225f9081bc6f">

2023-07-05 22:45 UTC, mckent05 commented on index.html
> +    </section>
- You have done well so far, but please remember to stick to the design template in terms of layout, spacing, borders, font color, background color, etc. The background color for this section is not the same as the given design template. Please fix this for both mobile and desktop versions🙏 

- In the mobile version, the section marked in the image below is not styled as it is in the given design template, please fix this 🙏. It is important to replicate the design template to give confidence to recruiters in our ability 👍 
Your project:
<img width="291" alt="sfjwrsgwr" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/4ebe10c0-6474-46d3-889e-0a55df857342">

Design template:
<img width="332" alt="rergerges" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/13f1f46f-ec8e-4979-a84d-a47e805b281f">

2023-07-05 22:45 UTC, mckent05 commented on index.html
> +            </ul>
- According to the project requirements, you are to ensure that the entire speaker section is rendered dynamically using JavaScript, please remove all HTML templates for this section and render using only Javascript 👍 👍. Please fix this 😄  
- Also, please ensure that the images for the individual speakers are styled according to the design template. I suggest making them a little bit bigger. Please fix this for both mobile and desktop version 👍 👍 
Your project:
<img width="506" alt="trergrk" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/8d9ece94-620b-4720-a369-e768d8d57b2a">

Design template:
<img width="474" alt="wfefwae" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/fbabdbc2-d5e2-48b5-95ca-5b3db51069a7">

2023-07-05 22:45 UTC, mckent05 commented on index.html
> +                        <li class="company1-logo"><span> <img class="img2-logo" src="./assets/images/googlekorea 1.svg" alt="microsoft"></span></li>
- Good job done so far, but please it is important to stick to the layout in the original design, you have added too many sponsors in your sponsor section. I suggest you style and design this section accordingly. Please fix this 😄 
Your project:
<img width="591" alt="erreev" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/4f7abef7-13c0-4345-9867-4407a46e418a">

Design template:
<img width="629" alt="wefefwf" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/e8a65a11-3d9e-4cd6-b2ed-59ab63f632a4">

2023-07-05 22:45 UTC, mckent05 commented on about.html
> +    </section>
- Good job done so far, but please note that as much as you are required to personalize the content of your project, it is still important to stick to the design layout, spacing, colors etc. There are two missing sections in your project, the Logo section and the `previous summit section`. Please, follow strictly the layout of the design template to give confidence to recruiters in your ability to replicate exact business requirements. Please fix this 🙏 
Your project:
-Please design for both desktop and mobile versions accordingly 👍 👍 
<img width="629" alt="erergergke" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/03a1449c-c2e3-4d4a-9c50-939a702df0ac">

Design template:
<img width="557" alt="wegqeg" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/e9a4dfc6-1173-435b-bda3-fa53d607d228">

- Also, on the mobile version of the About page, the `partner` section is missing, please include this section in your design 🙏 
Design template:
<img width="318" alt="rgqwg3" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/669e834c-37e9-4b27-9a26-eae9234dc9a1">

2023-07-05 22:45 UTC, mckent05 commented on about.html
> +                        <li class="company-logo"><span> <img class="img-logo" src="./assets/images/mozilla.svg" alt="Mozilla"></span></li>
- Please note that to ensure your HTML is readable and easy to maintain, it is not advisable to leave commented-out code on your page. Please ensure that only the needed code or HTML template is present on your page 👍

2023-07-05 22:45 UTC, mckent05 commented on about.html
> +            </article>
- You have not styled this section of your project correctly, please note that in the mobile version, the footer has a dark background color, while in the desktop version, the footer has a white background color. Please fix this 🙏
Your project:
Mobile version:
<img width="345" alt="ewefwefwef" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/1c09bcf3-56dc-4a8a-ab27-1a801b66a9ec">
Desktop version:
<img width="512" alt="eruerer" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/bd3ee7fa-3fbc-4d9c-8fd7-7f1ade7ecf48">

Design template:
Mobile version:
<img width="304" alt="gergerv" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/0a650689-ee01-455b-997e-ff1c5e18bc51">
Desktop version:
<img width="556" alt="gwfwg" src="https://github.com/Bettenoch/Web_Development_Course/assets/73607512/66063a65-8c95-4db1-994a-cab8be3ac6a5">

2023-07-05 22:45 UTC, mckent05 commented on about.html
> +            </article>
- Good job done so far, but please style this section of the page according to the design template. Please stick to the layout, font color, spacing, background color etc. please fix this 🙏

2023-07-06 09:46 UTC, Bettenoch commented
Hello @mckent05 thank you for you review comments. On the Logo section and the previous summit sections I changed the text to suite my content for a web development course. I was wondering if it is a must I use a logo instead of another image.

2023-07-06 10:39 UTC, nedjwab approved these changes
# 🟢 Project Approved! 🏆

## Hi  @Bettenoch    👋

Your project is complete! ✔️✔ , I loved your work, it looks great 🔥🔥🔥🔥 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors

- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 12:14 UTC, merged